### ISSUE TITLE
Possible syncing problems?

### ISSUE THREAD

**Issue by ewadding** [dsi-icl/optimise#1437]
We have noticed that when sites update their data, it sometimes takes much longer than expected (days or weeks) for the changes to be reflected on the central database.

I am not sure if this is a genuine software problem, or if the sites are simply doing something wrong, such as not allowing the laptops to connect to the network frequently/long enough.  As a first step, is it worth checking the logs to see how often each site laptop has been connecting to the central database?

**Comment by fguitton** [comment]
Provided internet connectivity is available, the software will attempt to synchronize every 15 minutes (when in use obviously). For site running a version prior to `1.19.5` there is a known issue preventing proper synchronization due to a SSL root certificate validation error, linked to the reclassification of Let's Encrypt CA which is used server side. We pushed version `1.19.5` to address this problem. Any other instance of synchronization would likely be because site aren't using the laptops in shorter intervals.
