### ISSUE TITLE
Audit of the user behavior format

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#151]
The question raised from the meeting @epissari @sou-c  and I got the 25th of May was about the format we should use to store the data from the user's activity on the software.
Three possibilities were given:

1. Store the data in the same database we use for the medical data (patient / users / tests / and so on) and store it in another table.
 - Pros:
   - We manage only one database.
 - Cons: 
   - The database will store different type of data that shouldn't be in the same container.
   - If there's a lot of traffic, the database will have a lot of query and could lead to access problems.

2. Store the data in another database alongside of the 'medical' database.
 - Pros : 
   - Better architecture and more logical choice.
   - Division of the traffic.
- Cons : 
  - Require a second connection in the server.

3. Store the data in a log file system. (Or can be a feature)
 - Pros : 
   - Faster and easier to implement.
   - Outdated data can be managed easier
   - Lots of library that can be used to create this system.
 - Cons : 
   - It's not in a database and can't be analyzed for future features (e.g. proposition of actions to the users).
   - The file must be formatted and secured.

We must choose something smart to not lose time.

**Comment by fguitton** [comment]
@Radiateurs, I think I would rule out option 3, while application logs are one thing (and can be dumped on the hard drive), user interaction logs are **absolutely** a feature of the application !

As such they should be treated like any other functional part of the application. Since you are using SQLite at present, you could imagine 2 SQLite files (transposed to two separate databases on a single MySQL instance, or two fully separated SQL instance). But you can simply use the same database.

Traffic on local computer would generate less then 1 transation per second on 0.99 confidence interval and on a centralise system less then 10 transactions per second with similar confidence. Also, database can (and are at DSI) load-balanced. You are never going to max out your IRQs. We talk about traffic when this thing gets 10000+ connections per second.

I would go option 1
