### ISSUE TITLE
PATIENT --> alias_id field

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#156]
I was wondering what was the purpose of the field "alias_id" in the table Patient.
Is it mandatory or can we get rid of it ?

**Comment by sou-c** [comment]
i think its mandatory in a sense that the people entering patient detail will be entering their own previously generated ids for the patients and would likely use those to search (thats why most of the functions are searching through alias_id instead)..now i don't know how exactly this will work since there are some discussion about whether people are gonna use NHS num, or some kind of internal id per hospital or per study

**Comment by Radiateurs** [comment]
Alright, seems legit ! Well done ;)
