### ISSUE TITLE
DELETED field in tables

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise#158]
The actual type of the deleted field is TEXT NOT NULL.
The things is we can improve the database analysis by allowing this field to be NULL. By doing this the request will look if the field is assigned either than looking at the actual value of it which can save us a small amount of time but still improve it.
(NULL --> not deleted | Assigned with a value --> deleted).

**Comment by sou-c** [comment]
try changing all the knex().where({deleted: 0}) and knex().where('deleted', 0) to knex('users').whereNull('deleted')

**Comment by sou-c** [comment]
i think at first i went for deleted=0 because i don't want someone to attach {deleted: blablabla} in their POST body, like POST /api/patients {"alias_id": "chonsou", "deleted": "blablabalba"} (don't know why they would do that, but just in case). so the function that creates entry (in utils/controller-utils.js) added / modify the "deleted" key to 0 to prevent the API user putting whatever they want. but of course you can change it to NULL. At that time there wasnt much time i didn't bother to check if knex write null values if {deleted: null} or only if the key is not present. so i went for '0' instead. but it's entirely up to you

**Comment by fguitton** [comment]
@sou-c You should probably operate some sort of sanitization to the input at all time anyway. It is important to avoid Object Injection Sinks and Direct Injection Attack to prevent security breaches. What this means is never trust an object of which the structure was formulated by a thrid-party, always reconstruct. Which is why it's important to define strict APIs.
