### ISSUE TITLE
Baseline data collection screen shows at every new visit creation

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise#1713]
**Describe the bug**
Baseline data collection screen shows at every new visit creation

**To Reproduce**
1. Add follow-up visit to existing patient

**Smartphone (please complete the following information):**
 - Version 2.1.0

**Comment by lbianchi222** [comment]
Dear Florian,
I am sorry to be bothering you again, but I learnt from the Site the problem is still ongoing.
Is there any chance you / the new Optimise developer can look into this at your/their earliest convenience?
This is impacting on site activity, and it is quite crucial for us to keep everyone engaged at this stage in order to meet the Study milestones.
Please let me know if there is anything I can do to help?
Thank you
Best wishes,
Lucia

**Comment by fguitton** [comment]
I just want to note here (this was treated via email) that the current behaviour is indeed expected. We are now going through it with the site.

**Comment by lbianchi222** [comment]
Thank you for the update Florian, much appreciated
